inherit_from: .rubocop_todo.yml

# For tests, having braces around the expected value helps
# with clarity:
#
#   assert solve('question'), { a: [1, 2, 3] }
#
Style/BracesAroundHashParameters:
  Enabled: false

# Documentation on classes is great, if this were a realistic
# production product.
Style/Documentation:
  Enabled: false

# Frozen-by-default string literals are also great in production
# products; but the magic comment detracts from solutions.
Style/FrozenStringLiteralComment:
  Enabled: false

# With the tests being written I end up with a mixture of %i[] and [] arrays.
# I also happen to find these shorthand definitions to be far less legible than
# their explicit counterparts -- this recommendation leans far to heavily on
# prioritizing fewer keystrokes with no real benefit.
Style/SymbolArray:
  Enabled: false

# While this metric can be useful for other methods, it will report
# failures for our testing methods.
Metrics/AbcSize:
  Enabled: false

# We want our test methods to be self-contained, so we can simply exclude
# them from method length checks.
Metrics/MethodLength:
  Max: 15
  ExcludedMethods:
    - tests

# Short helper methods don't need longer variable names.
Naming/MethodParameterName:
  Enabled: false
